### ISSUE TITLE
Test the teaching-support code

### ISSUE THREAD

**Issue by ilundberg** [fragilefamilieschallenge/teaching-support#1]
Within the [lesson plan for participants](https://github.com/fragilefamilieschallenge/teaching-support/blob/main/lesson_plan_masscollaboration_participant.md), the preparation section tells them they can web source [our code](https://github.com/fragilefamilieschallenge/teaching-support/blob/main/prepare_simple_data.R) to produce the simplified version of the Challenge file. Could someone else test this to see if it works for you? I am happy to hear ideas for improvements.

**Comment by msalganik** [comment]
As we discussed, we are going to provide this code as is.  Thanks @ilundberg
